# Generated by Django 2.2.2 on 2019-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20190719_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionconfig',
            name='block_time_generation',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='electionconfig',
            name='min_votes_in_block',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='electionconfig',
            name='min_votes_in_last_block',
            field=models.IntegerField(default=6),
        ),
    ]
