# Generated by Django 2.2.2 on 2019-07-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_hash', models.CharField(max_length=128)),
                ('parent_hash', models.CharField(max_length=128)),
                ('database_hash', models.TextField()),
                ('hash_of_database_hash', models.CharField(max_length=128)),
                ('source_code_hash', models.TextField()),
                ('hash_of_source_code_hash', models.CharField(max_length=128)),
                ('candidate_votes', models.TextField(blank=True, null=True)),
                ('electors', models.TextField(blank=True, null=True)),
                ('timestamp_iso', models.CharField(max_length=30)),
                ('total_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlockStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlockNo', models.IntegerField(unique=True)),
                ('ParentHash', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
    ]
