# Generated by Django 2.2.2 on 2019-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bblock',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
